# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hd7rI_z1LTasc77-hQ2DHNk06OmwUYPW
"""

!pip install -U kaleido
import numpy as np
import pandas as pd
import plotly.express as px
from textblob import TextBlob

df = pd.read_csv('netflix_titles.csv')

#number of rows and columns
df.shape

#preview first 5 rows of data
df.head()

#previe columns
df.columns

x = df.groupby(['rating']).size().reset_index(name='counts')
print(x)

from os import name
pieChart=px.pie(x, values='counts', names= 'rating', title='Distribution of content ratings on Netflix')
pieChart.show()

#Analyzing the top 5 Directors on Netflix
df['director']=df['director'].fillna('Director not specified')
df.head()

directors_list = pd.DataFrame()
print(directors_list)

directors_list = df['director'].str.split(',', expand=True).stack()
print(directors_list)

directors_list = directors_list.to_frame()
print(directors_list)

directors_list.columns = ['Director']
print(directors_list)

#how much content did our directors create
directors = directors_list.groupby(['Director']).size().reset_index(name='Total Count')
print(directors)

print(directors)